# Imagem base oficial do Python
FROM python:3.11-slim
# Copia o arquivo python para o container
COPY soma_aleatoria.py /app/soma_aleatoria.py

# Define o diretório de trabalho
WORKDIR /app

# Comando para executar o arquivo python
CMD ["python", "soma_aleatoria.py"]